pipeline{
    agent any
    tools{
        maven "M2_HOME"
    }
    stages{
        stage("build"){
            steps{
                sh 'mvn validate  compile  install package test '
            }
        }
        stage("upload artifactory"){
            steps{
                sh 'curl -uadmin:AP43csQfawThgsFYocyVrexhQ9x -T  target/bio*.jar  "http://54.144.133.83:8081/artifactory/take32/geosolution1/bio_${BUILD_ID}.jar"'
            }
        }
    }
}