pipeline{
    agent any
    tools{
        maven "M2_HOME"
    }
    stages{
        stage("build"){
            steps{
                sh 'mvn validate  compile  install package test '
            }
        }
    }
}